#
# This Dockerfile is used for locally running Playwright in a Linux environment.
# We do this to ensure our reference images for visual regression tests are the same during development and in CI.
#

FROM mcr.microsoft.com/playwright:v1.41.0-focal

WORKDIR /work

COPY package.json ./

RUN npm install --frozen-lockfile

COPY playwright.config.js test-runner-jest.config.js ./

COPY .storybook/ .storybook/
