services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    network_mode: host
    volumes:
      # Mount the whole frontend/ directory to avoid to a new Docker image being generated each time
      # frontend code changes. Also, this allows frontend/__snapshots__/ to be updated.
      - "./stories:/work/stories"
      - "./__snapshots__:/work/__snapshorts__"
      - "./playwright:/work/playwright"
      - "./playwright-report:/work/playwright-report"
      - "./test-results:/work/test-results"
